export default {
  en: {
    BOOKING_DETAIL_HEADING: 'Flight Domestic Booking',
    CONTACT_DETAILS: 'Contact Details',
    BOOKING_DETAILS: 'Booking Details',
    PASSENGER_DETAILS: 'Passenger Details',
    PAX: {
      EMAIL: 'Email',
      TELP: 'Phone Number',
      DOB: 'Date of Birth',
      NATIONALITY: 'Nationality',
      ID_TYPE: 'Identity Type',
      ID_NO: 'Identity Number',
      ID_EXPIRY: 'Date of Expiry',
      ID_COI: 'Country of Issue',
    },
    CHECK_DETAILS: 'Check Your Booking',
    DEPARTURE: 'Departure',
    RETURN: 'Return',
    PROMO_CODE: 'Promo Code',
    PAY_NOW: 'Pay Now',
  },
  id: {
    BOOKING_DETAIL_HEADING: 'Pemesanan Pesawat Domestik',
    CONTACT_DETAILS: 'Detail Pemesan',
    BOOKING_DETAILS: 'Detail Pemesanan',
    PASSENGER_DETAILS: 'Detail Penumpang',
    PAX: {
      EMAIL: 'Email',
      TELP: 'Nomor Telepon',
      DOB: 'Tanggal Lahir',
      NATIONALITY: 'Kewarganegaraan',
      ID_TYPE: 'Tipe Identitas',
      ID_NO: 'No. Identitas',
      ID_EXPIRY: 'Tanggal Habis Berlaku',
      ID_COI: 'Negara yang Mengeluarkan',
    },
    CHECK_DETAILS: 'Cek Pemesanan Kamu',
    DEPARTURE: 'Keberangkatan',
    RETURN: 'Kepulangan',
    PROMO_CODE: 'Kode Promo',
    PAY_NOW: 'Bayar Sekarang',
  },
};
