export default {
  en: {
    BOOKING_DETAIL_HEADING: 'Flight Domestic Booking',
    CONTACT_DETAILS: 'Contact Details',
    BOOKING_DETAILS: 'Booking Details',
    PASSENGER_DETAILS: 'Passenger Details',
    PAX: {
      EMAIL: 'Email',
      TELP: 'Phone Number',
      DOB: 'Date of Birth',
      NATIONALITY: 'Nationality',
      ID_TYPE: 'Identity Type',
      ID_NO: 'Identity Number',
      ID_EXPIRY: 'Date of Expiry',
      ID_COI: 'Country of Issue',
    },
    CHECK_DETAILS: 'Check Your Booking',
    DEPARTURE: 'Departure',
    RETURN: 'Return',
    PROMO_CODE: 'Promo Code',
    PAY_NOW: 'Pay Now',
    PTL: 'Payment Time Limit',
    ADD_COUPON: 'Add',
    APPLY_COUPON: 'APPLY',
    AGREEMENT:
      'By clicking "Pay Now", you have agreed to the Terms & Conditions, as well as the Privacy Policy',

    Passport: 'Passport',
    NIK: 'ID Card',
    price_detail: 'Price Detail',
    got_promo: 'Got Promo Code?',
    input_promo_code: 'Input Promo Code',
    transit_for: 'Transit for {time} in {city} ({code})',
  },
  id: {
    BOOKING_DETAIL_HEADING: 'Pemesanan Pesawat Domestik',
    CONTACT_DETAILS: 'Detail Pemesan',
    BOOKING_DETAILS: 'Detail Pemesanan',
    PASSENGER_DETAILS: 'Detail Penumpang',
    PAX: {
      EMAIL: 'Email',
      TELP: 'Nomor Telepon',
      DOB: 'Tanggal Lahir',
      NATIONALITY: 'Kewarganegaraan',
      ID_TYPE: 'Tipe Identitas',
      ID_NO: 'No. Identitas',
      ID_EXPIRY: 'Tanggal Habis Berlaku',
      ID_COI: 'Negara yang Mengeluarkan',
    },
    CHECK_DETAILS: 'Cek Pemesanan Kamu',
    DEPARTURE: 'Keberangkatan',
    RETURN: 'Kepulangan',
    PROMO_CODE: 'Kode Promo',
    PAY_NOW: 'Bayar Sekarang',
    PTL: 'Batas Waktu Pembayaran',
    ADD_COUPON: 'Tambah',
    APPLY_COUPON: 'GUNAKAN',
    AGREEMENT:
      'Dengan klik "Bayar Sekarang", kamu telah menyetujui Syarat & Ketentuan, serta Kebijakan Privasi.',

    Passport: 'Paspor',
    NIK: 'NIK',
    price_detail: 'Detail Harga',
    got_promo: 'Punya Kode Promo?',
    input_promo_code: 'Masukkan kode promo',
    transit_for: 'Transit selama {time} di {city} ({code})',
  },
};
