export default {
    en: {
        title_about_misteraladin: 'ABOUT MISTER ALADIN',
        about_us: 'About Us',
        pres: 'Press',
        be_ourpartner: 'Be Our Partner',
        title_product:'PRODUCTS',
        aladin_mall: 'AladinMall',
        aladin_xplore: 'AladinXplore',
        hotels: 'Hotels',
        dom_flights: 'Dom. Flights',
        intl_flights: 'Intl. Flights',
        trains: 'Trains',
        desa_wisata: 'Desa Wisata',
        title_others: 'OTHERS',
        faq:'FAQ',
        privacy_policy: 'Privacy Policy',
        terms_condition: 'Terms & Condition',
        title_followus: 'FOLLOW US',
    },
    id: {
        title_about_misteraladin: 'TENTANG MISTER ALADIN',
        about_us: 'Tentang Kami',
        pres: 'Pers',
        be_ourpartner: 'Jadi Mitra Kami',
        title_product:'PRODUK',
        aladin_mall: 'AladinMall',
        aladin_xplore: 'AladinXplore',
        hotels: 'Hotel',
        dom_flights: 'Pesawat Dom.',
        intl_flights: 'Pesawat Intl.',
        trains: 'Kereta Api',
        desa_wisata: 'Desa Wisata',
        title_others: 'LAINNYA',
        faq:'FAQ',
        privacy_policy: 'Kebijakan Privasi',
        terms_condition: 'Syarat & Ketentuan',
        title_followus: 'IKUTI KAMI',
    },
};