export default {
  en: {
    booking_details: "Booking Details",
    traveler_details: "Traveler Details",
    transit_in: '{time} transit in {place} ({code})',
    price_departure: 'Depature Price',
    price_return: 'Return Price',
    next: "Next",
    want_to_save: "Want to save even more? Don't forget to log in.",
    login: "Login",
    passenger_info: "Attention: the passenger's name must be the same as the passport (international flights), or KTP/SIM (domestic flights). Passenger data cannot be changed after this page.",
    enter_details: "Enter details",
    direct: "Direct",
    transit: "{total}x Transit",
    departure: "Departure",
    return: "Return",
    see_detail: "See Detail",
    failed_to_order: "Order could not be processed Sorry! There was a problem in processing your order. Please select an airline or other available date.",
    let_continue: "Continue",
    continue: "Continue",
    check_again: "Check Again",
    close: "Close",
    order_process_title: "Whoos, don't go anywhere!",
    order_process_text: "Your order is being processed. I promise, it won't be long. Just a few minutes, really.",
    order_confirmation_text: "Make sure your data is correct before continuing",
    customer_data: "Customer Data",
    passenger_data: "Passenger Data",
    adult: "Adult",
    child: "Child",
    infant: "Infant",
    mr: 'Mr.',
    mrs: 'Mrs.',
    ms: 'Ms.',
    mstr: 'Mstr.',
    save: "Save",
    cancel: "Cancel",
    name_instruction_title: "Name Writing Instructions",
    name_instruction_desc: '<ul> <li> <b>For Indonesian Citizens</b>, name and NIK must be the same as registered. For foreigners, use the name and number listed on the passport. <b>For foreigners</b>, use the name and number listed on the passport. </li> <li> If you do not have a "middle name" <b>(example: Ari Wibowo)</b>, leave the middle name blank and only fill in the first name <b>(example: Ari)</b> and last name <b>(example: Wibowo)</b> </li> <li> If you only have one name <b>(example: Kartini)</b>, please leave middle name blank and fill last name with first name <b>(example: Kartini Kartini)</b>. </li> </ul>',
    understand: "Understand",
    passport_info: "Hubungi Personal Assistant jika kamu belum memiliki paspor",
    title: "Title",
    first_name: "First Name",
    middle_name: "Middle Name",
    last_name: "Last Name",
    email: "Email",
    country_code: "Country Code",
    phone_number: "Phone Number",
    citizenship: "Citizenship",
    date_of_birth: "Date of birth",
    indentity_type: "Identity Type",
    nik: "NIK",
    passport: "Passport",
    identity_number: "Identity Number",
    passport_number: "Passport Number",
    passport_expiration_date: "Expiration Date",
    passport_expiration_info: "Important: passport valid for at least 6 months from the date of arrival at the destination.",
    passport_issuing_country: "Issuing Country",
    passenger_child_info: "Child Passengers (2 - 12 years old)",
    passenger_infant_info: "Infant Passengers (< 2 years)",
    identity_number_child: "For child and infant passengers, enter the number shown on the Family Card.",
    select_country: "Select Country",
    enter_country_name: 'Enter Country Name',
  },
  id: {
    booking_details: "Detail Pemesanan",
    traveler_details: "Detail Penumpang",
    transit_in: 'Transit {time} di {place} ({code})',
    price_departure: 'Harga Keberangkatan',
    price_return: 'Harga Kepulangan',
    next: "Selanjutnya",
    want_to_save: "Mau lebih hemat? Jangan lupa log in, ya.",
    login: "Login",
    passenger_info: "Perhatian: nama penumpang harus sama dengan paspor (penerbangan internasional), atau KTP/SIM (penerbangan domestik). Data penumpang tidak dapat diubah setelah halaman ini.",
    enter_details: "Isi detail",
    direct: "Langsung",
    transit: "{total}x Transit",
    departure: "Keberangkatan",
    return: "Kepulangan",
    see_detail: "Lihat Detail",
    failed_to_order: "Pemesanan tidak dapat diproses Mohon maaf! Ada kendala dalam pemrosesan pemesanan kamu. Silakan pilih maskapai atau tanggal lainnya yang tersedia.",
    let_continue: "Lanjutkan",
    continue: "Lanjut",
    check_again: "Cek Lagi",
    close: "Tutup",
    order_process_title: "Eits, jangan kemana-mana!",
    order_process_text: "Pemesanan kamu sedang diproses. Janji, deh, gak akan lama. Cuma beberapa menit aja, kok.",
    order_confirmation_text: "Pastikan data kamu sudah benar sebelum melanjutkan",
    customer_data: "Data Pemesan",
    passenger_data: "Data Penumpang",
    adult: "Dewasa",
    child: "Anak",
    infant: "Bayi",
    mr: 'Tuan',
    mrs: 'Nyonya',
    ms: 'Nona',
    mstr: 'Tuan',
    save: "Simpan",
    cancel: "Batal",
    name_instruction_title: "Instruksi Penulisan Nama",
    name_instruction_desc: '<ul> <li> <b>Untuk WNI</b>, nama dan NIK harus sama dengan yang terdaftar. Untuk WNA, gunakan nama dan nomor yang tercantum di paspor. </li> <li> Jika kamu tidak memiliki "nama tengah" <b>(contoh: Ari Wibowo)</b>, kosongkan bagian nama tengah dan hanya isi nama depan <b>(contoh: Ari)</b> dan nama akhir <b>(contoh: Wibowo)</b> </li> <li> Jika kamu hanya memiliki satu nama <b>(contoh: Kartini)</b>, harap kosongkan nama tengah dan mengisi nama belakang dengan nama depan <b>(contoh: Kartini Kartini)</b>. </li> </ul>',
    understand: "Mengerti",
    passport_info: "Contact the Personal Assistant if you don't have a passport yet",
    title: "Title",
    first_name: "Nama Depan",
    middle_name: "Nama Tengah",
    last_name: "Nama Belakang",
    email: "Email",
    country_code: "Kode Negara",
    phone_number: "Nomor Telepon",
    citizenship: "Kewarganegaraan",
    date_of_birth: "Tanggal Lahir",
    indentity_type: "Identity Type",
    nik: "NIK",
    passport: "Passpor",
    identity_number: "No. Identitas",
    passport_number: "No. Paspor",
    passport_expiration_date: "Tanggal Habis Berlaku",
    passport_expiration_info: "Penting: paspor berlaku minimal 6 bulan dari tanggal kedatangan di destinasi tujuan.",
    passport_issuing_country: "Negara yang Mengeluarkan",
    passenger_child_info: "Penumpang Anak (2 - 12 tahun)",
    passenger_infant_info: "Penumpang Bayi (< 2 tahun)",
    identity_number_child: "Untuk penumpang anak dan bayi, masukkan nomor yang tertera di Kartu Keluarga.",
    select_country: "Pilih Negara",
    enter_country_name: 'Ketik Nama Negara',
  },
};
