export default {
  en: {
    BOOKING_DETAIL_HEADING: 'Flight International Booking',
    CONTACT_DETAILS: 'Contact Details',
    BOOKING_DETAILS: 'Booking Details',
    PASSENGER_DETAILS: 'Passenger Details',
    FORM: {
      TITLE: 'Title',
      FIRST: 'First Name',
      MIDDLE: 'Middle Name',
      LAST: 'Last Name',
      INFORMATION:
        '<li>For Indonesians, name and ID number must exactly match your ID card. For foreigners, name and number must exactly match your passport.</li> <li>If you don\'t have a "middle name" (example: "Ari Wibowo"), please only fill out your first name (example: Ari) and last name (example: Wibowo)</li> <li>If you only have "first name" (example: "Kartini"), please fill out both first and last names with the same name (example: Kartini Kartini).</li>',
      EMAIL: 'Email',
      TELP: 'Phone Number',
      NATIONALITY: 'Nationality',
      DOB: 'Date of Birth',
      DATE_FORMAT: 'dd/mm/yy',
      NIK_PLACEHOLDER: 'ID Number minimum 16 characters',
      IDTYPE: 'Identity Type',
      IDNO: 'ID Card Number',
      PASSNO: 'Passport Number',
      PASSNO_PLACEHOLDER: 'Min. 6 and Max 10 characters',
      DOE: 'Date of Expiry',
      COI: 'Country of Issue',
      PASSPORT_NOTICE:
        'Important: passport must valid for at least 6 months from the date of arrival in destination.',
    },
    PASSENGER: {
      MR: 'Mr.',
      MRS: 'Mrs.',
      MS: 'Ms.',
      MSTR: 'Mstr.',
    },
    SAME_AS_CONTACT: 'Same as contact',
    VALIDATION: {
      REQUIRED: 'Field is required.',
      NAME: 'Must be between 1 - 50 characters.',
      MIDDLENAME: 'Must not exceed 50 characters.',
      PHONE_MIN: 'Phone number must contain at least 9 digits',
      PHONE_MAX: 'Phone number must contain maximum 13 digits',
      EMAIL: 'Please enter a valid email address',
      NIK: 'Enter 16 numeric characters.',
      PASSPORT: 'Enter minimum 6 or maximum 10 alphanumeric characters.',
      ALPHANUM: 'Must be alphanumeric',
    },
    CONFIRM: {
      BEFORE_POST: 'Pastikan data kamu sudah benar sebelum melanjutkan',
      BUTTON: 'Confirm',
    },
    ERROR: {
      MATCH_NAME: 'Please fill in your name in the contact details first.',
    },
    ATTENTION:
      'Attention: name of passenger must match your passport (international flights), or KTP/SIM (domestic flights). Passenger data cannot be changed after this page.',

    want_to_save: "Want to save even more? Don't forget to log in.",
    passenger_adult: 'Adult Passenger',
    passenger_child: 'Child Passenger',
    passenger_infant: 'Infant Passenger',
    nik: 'ID Card',
    passport: 'Passport',
    order_cant_processed:
      'Order cannot be processed Sorry! There was a problem in processing your order. Please select an airline or other available date.',
    return_main_page: 'Return to Main Page',
    transit_for: 'Transit for {time} in {city} ({code})',

    departure: 'Departure',
    return: 'Return',
    departure_price: 'Departure Price',
    return_price: 'Return Price',
    booking_details: 'Booking Details',
    traveler_details: 'Traveler Details',
    transit_in: '{time} transit in {place} ({code})',
    price_departure: 'Depature Price',
    price_return: 'Return Price',
    next: 'Next',
    login: 'Login',
    passenger_info:
      "Attention: the passenger's name must be the same as the passport (international flights), or KTP/SIM (domestic flights). Passenger data cannot be changed after this page.",
    enter_details: 'Enter details',
    direct: 'Direct',
    transit: '{total}x Transit',
    see_detail: 'See Detail',
    failed_to_order:
      'Order could not be processed Sorry! There was a problem in processing your order. Please select an airline or other available date.',
    let_continue: 'Continue',
    continue: 'Continue',
    check_again: 'Check Again',
    close: 'Close',
    order_process_title: "Whoos, don't go anywhere!",
    order_process_text:
      "Your order is being processed. I promise, it won't be long. Just a few minutes, really.",
    order_confirmation_text: 'Make sure your data is correct before continuing',
    customer_data: 'Contact Details',
    passenger_data: 'Passenger Data',
    adult: 'Adult',
    child: 'Child',
    infant: 'Infant',
    mr: 'Mr.',
    mrs: 'Mrs.',
    ms: 'Ms.',
    mstr: 'Mstr.',
    save: 'Confirm',
    cancel: 'Cancel',
    name_instruction_title: 'Name Writing Instructions',
    name_instruction_desc:
      '<ul> <li> <b>For Indonesians</b>, name and ID number must exactly match your ID card. <b>For foreigners</b>, name and number must exactly match your passport. </li> <li> If you don\'t have a "middle name" <b>(example: Ari Wibowo)</b>, please only fill out your first name <b>(example: Ari)</b> and last name <b>(example: Wibowo)</b> </li> <li> If you only have "first name" <b>(example: Kartini)</b>, please fill out both first and last names with the same name <b>(example: Kartini Kartini)</b>. </li> </ul>',
    understand: 'Understand',
    passport_info: 'Hubungi Personal Assistant jika kamu belum memiliki paspor',
    title: 'Title',
    first_name: 'First Name',
    middle_name: 'Middle Name',
    last_name: 'Last Name',
    email: 'Email',
    country_code: 'Country Code',
    phone_number: 'Phone Number',
    citizenship: 'Nationality',
    date_of_birth: 'Date of birth',
    indentity_type: 'Identity Type',
    identity_number: 'ID Card Number',
    passport_number: 'Passport Number',
    passport_expiration_date: 'Date of Expiry',
    passport_expiration_info:
      'Important: passport valid for at least 6 months from the date of arrival at the destination.',
    passport_issuing_country: 'Country of Issue',
    passenger_child_info: 'Child Passengers (2 - 12 years old)',
    passenger_infant_info: 'Infant Passengers (< 2 years)',
    identity_number_child:
      'For child and infant passengers, enter the number shown on the Family Card.',
    select_country: 'Select Country',
    enter_country_name: 'Enter Country Name',
    BOOKING_LOADING_TITLE: 'Sit tight!',
    BOOKING_LODING_TEXT:
      'Your booking is being processed. This won’t take long, we promise.',
    CHANGE: 'Change',
    POPUP_CONFIRM: {
      MESSAGE: 'Please make sure your data is accurate before continuing.',
      BUTTON_CANCEL: 'Check Again',
      BUTTON_CONFIRM: 'Continue',
    },
    PAX_ID_INFO:
      'For children and infants, please enter the numbers stated on your Family Card.',
    PAX_DOB_INFO: {
      child: 'Child Passenger (2 - 12 years)',
      infant: 'Infant Passenger (< 2 years)',
    },
  },
  id: {
    BOOKING_DETAIL_HEADING: 'Pemesanan Pesawat Internasional',
    CONTACT_DETAILS: 'Detail Pemesan',
    BOOKING_DETAILS: 'Detail Pemesanan',
    PASSENGER_DETAILS: 'Detail Penumpang',
    FORM: {
      TITLE: 'Titel',
      FIRST: 'Nama Depan',
      MIDDLE: 'Nama Tengah',
      LAST: 'Nama Belakang',
      INFORMATION:
        '<li>Untuk WNI, nama dan NIK harus sama dengan yang terdaftar. Untuk WNA, gunakan nama dan nomor yang tercantum di paspor. Untuk WNA , gunakan nama dan nomor vang tercantum di paspor.</li> <li>Jika kamu tidak memiliki "nama tengah" (contoh: Ari Wibowo), kosongkan bagian nama tengah dan hanya isi nama depan (contoh: Ari) dan nama akhir (contoh: Wibowo)</li> <li>Jika kamu hanya memiliki satu nama (contoh: Kartini), harap mengosongkan nama tengah dan mengisi nama belakang dengan nama depan (contoh: Kartini Kartini).</li>',
      EMAIL: 'Email',
      TELP: 'Nomor Telepon',
      NATIONALITY: 'Kewarganegaraan',
      DOB: 'Tanggal Lahir',
      DATE_FORMAT: 'hh/bb/tt',
      NIK_PLACEHOLDER: 'Nomor NIK minimal 16 karakter',
      IDTYPE: 'Tipe Identitas',
      IDNO: 'Nomor NIK',
      PASSNO: 'Nomor Paspor',
      PASSNO_PLACEHOLDER: 'Min. 6 dan Maks. 10 karakter',
      DOE: 'Tanggal Habis Berlaku',
      COI: 'Negara Yang Mengeluarkan',
      PASSPORT_NOTICE:
        'Perhatian: paspor berlaku minimal 6 bulan dari tanggal kedatangan di destinasi tujuan.',
    },
    PASSENGER: {
      MR: 'Tuan',
      MRS: 'Nyonya',
      MS: 'Nona',
      MSTR: 'Tuan',
    },
    SAME_AS_CONTACT: 'Sama seperti pemesan',
    VALIDATION: {
      REQUIRED: 'Wajib diisi.',
      NAME: 'Minimal 1 - 50 karakter.',
      MIDDLENAME: 'Maksimal 50 karakter.',
      PHONE_MIN: 'Nomor telepon minimal harus 9 digit',
      PHONE_MAX: 'Nomor telepon maksimal harus 13 digit',
      EMAIL: 'Format email kamu salah',
      NIK: 'Masukkan 16 karakter numerik.',
      PASSPORT: 'Masukkan minimal 6 atau maksimal 10 karakter alfanumerik.',
      ALPHANUM: 'Wajib alfanumerik',
    },
    CONFIRM: {
      BEFORE_POST: 'Pastikan data kamu sudah benar sebelum melanjutkan',
      BUTTON: 'Konfirmasi',
    },
    ERROR: {
      MATCH_NAME: 'Silahkan isi nama Anda pada detail kontak terlebih dahulu.',
    },
    ATTENTION:
      'Perhatian: nama penumpang harus sama dengan paspor (penerbangan internasional), atau KTP/SIM (penerbangan domestik). Data penumpang tidak dapat diubah setelah halaman ini.',

    want_to_save: 'Mau lebih hemat? Jangan lupa log in, ya.',
    passenger_adult: 'Penumpang Dewasa',
    passenger_child: 'Penumpang Anak',
    passenger_infant: 'Penumpang Bayi',
    nik: 'NIK',
    passport: 'Paspor',
    order_cant_processed:
      'Pemesanan tidak dapat diproses Mohon maaf! Ada kendala dalam pemrosesan pemesanan kamu. Silakan pilih maskapai atau tanggal lainnya yang tersedia.',
    return_main_page: 'Kembali ke Halaman Utama',
    transit_for: 'Transit selama {time} di {city} ({code})',
    departure: 'Keberangkatan',
    return: 'Kepulangan',
    departure_price: 'Harga Keberangkatan',
    return_price: 'Harga Kepulangan',
    booking_details: 'Detail Pemesanan',
    traveler_details: 'Detail Penumpang',
    transit_in: 'Transit {time} di {place} ({code})',
    price_departure: 'Harga Keberangkatan',
    price_return: 'Harga Kepulangan',
    next: 'Selanjutnya',
    login: 'Login',
    passenger_info:
      'Perhatian: nama penumpang harus sama dengan paspor (penerbangan internasional), atau KTP/SIM (penerbangan domestik). Data penumpang tidak dapat diubah setelah halaman ini.',
    enter_details: 'Isi detail',
    direct: 'Langsung',
    transit: '{total}x Transit',
    see_detail: 'Lihat Detail',
    failed_to_order:
      'Pemesanan tidak dapat diproses Mohon maaf! Ada kendala dalam pemrosesan pemesanan kamu. Silakan pilih maskapai atau tanggal lainnya yang tersedia.',
    let_continue: 'Lanjutkan',
    continue: 'Lanjut',
    check_again: 'Cek Lagi',
    close: 'Tutup',
    order_process_title: 'Eits, jangan kemana-mana!',
    order_process_text:
      'Pemesanan kamu sedang diproses. Janji, deh, gak akan lama. Cuma beberapa menit aja, kok.',
    order_confirmation_text:
      'Pastikan data kamu sudah benar sebelum melanjutkan',
    customer_data: 'Detail Pemesan',
    passenger_data: 'Data Penumpang',
    adult: 'Dewasa',
    child: 'Anak',
    infant: 'Bayi',
    mr: 'Tuan',
    mrs: 'Nyonya',
    ms: 'Nona',
    mstr: 'Tuan',
    save: 'Konfirmasi',
    cancel: 'Batal',
    name_instruction_title: 'Instruksi Penulisan Nama',
    name_instruction_desc:
      '<ul> <li> <b>Untuk WNI</b>, nama dan NIK harus sama dengan yang terdaftar. Untuk WNA, gunakan nama dan nomor yang tercantum di paspor. <b>Untuk WNA</b>, gunakan nama dan nomor vang tercantum di paspor. </li> <li> Jika kamu tidak memiliki "nama tengah" <b>(contoh: Ari Wibowo)</b>, kosongkan bagian nama tengah dan hanya isi nama depan <b>(contoh: Ari)</b> dan nama akhir <b>(contoh: Wibowo)</b> </li> <li> Jika kamu hanya memiliki satu nama <b>(contoh: Kartini)</b>, harap kosongkan nama tengah dan mengisi nama belakang dengan nama depan <b>(contoh: Kartini Kartini)</b>. </li> </ul>',
    understand: 'Mengerti',
    passport_info:
      "Contact the Personal Assistant if you don't have a passport yet",
    title: 'Title',
    first_name: 'Nama Depan',
    middle_name: 'Nama Tengah',
    last_name: 'Nama Belakang',
    email: 'Email',
    country_code: 'Kode Negara',
    phone_number: 'Nomor Telepon',
    citizenship: 'Kewarganegaraan',
    date_of_birth: 'Tanggal Lahir',
    indentity_type: 'Tipe Identitas',
    identity_number: 'Nomor NIK',
    passport_number: 'Nomor Paspor',
    passport_expiration_date: 'Tanggal Habis Berlaku',
    passport_expiration_info:
      'Penting: paspor berlaku minimal 6 bulan dari tanggal kedatangan di destinasi tujuan.',
    passport_issuing_country: 'Negara yang Mengeluarkan',
    passenger_child_info: 'Penumpang Anak (2 - 12 tahun)',
    passenger_infant_info: 'Penumpang Bayi (< 2 tahun)',
    identity_number_child:
      'Untuk penumpang anak dan bayi, masukkan nomor yang tertera di Kartu Keluarga.',
    select_country: 'Pilih Negara',
    enter_country_name: 'Ketik Nama Negara',
    BOOKING_LOADING_TITLE: 'Eits, jangan ke mana-mana!',
    BOOKING_LODING_TEXT:
      'Pemesanan kamu sedang diproses. Janji, deh, gak akan lama. Cuma beberapa menit aja, kok.',
    CHANGE: 'Ubah',
    POPUP_CONFIRM: {
      MESSAGE: 'Pastikan data kamu sudah benar sebelum melanjutkan.',
      BUTTON_CANCEL: 'Cek Lagi',
      BUTTON_CONFIRM: 'Lanjut',
    },
    PAX_ID_INFO:
      'Untuk penumpang anak dan bayi, masukkan nomor yang tertera di Kartu Keluarga.',
    PAX_DOB_INFO: {
      child: 'Penumpang Anak (2 - 12 tahun)',
      infant: 'Penumpang Bayi (< 2 tahun)',
    },
  },
};
