export default {
  en: {
    BOOKING_DETAIL_HEADING: 'Flight Domestic Booking',
    CONTACT_DETAILS: 'Contact Details',
    BOOKING_DETAILS: 'Booking Details',
    PASSENGER_DETAILS: 'Passenger Details',
    FORM: {
      TITLE: 'Title',
      FIRST: 'First Name',
      MIDDLE: 'Middle Name',
      LAST: 'Last Name',
      INFORMATION:
        '<li>For Indonesians, name and ID number must exactly match your ID card. For foreigners, name and number must exactly match your passport.</li> <li>If you don\'t have a "middle name" (example: "Ari Wibowo"), please only fill out your first name (example: Ari) and last name (example: Wibowo)</li> <li>If you only have "first name" (example: "Kartini"), please fill out both first and last names with the same name (example: Kartini Kartini).</li>',
      EMAIL: 'Email',
      TELP: 'Phone Number',
      NATIONALITY: 'Nationality',
      DOB: 'Date of Birth',
      DATE_FORMAT: 'dd/mm/yy',
      NIK_PLACEHOLDER: 'ID Number minimum 16 characters',
      IDTYPE: 'Identity Type',
      IDNO: 'ID Card Number',
      PASSNO: 'Passport Number',
      PASSNO_PLACEHOLDER: 'Min. 6 and Max 10 characters',
      DOE: 'Date of Expiry',
      COI: 'Country of Issue',
      PASSPORT_NOTICE:
        'Important: passport must valid for at least 6 months from the date of arrival in destination.',
    },
    PASSENGER: {
      MR: 'Mr.',
      MRS: 'Mrs.',
      MS: 'Ms.',
    },
    SAME_AS_CONTACT: 'Same as contact',
    VALIDATION: {
      REQUIRED: 'Field is required.',
      NAME: 'Must be between 1 - 50 characters.',
      MIDDLENAME: 'Must not exceed 50 characters.',
      PHONE_MIN: 'Phone number must contain at least 9 digits',
      PHONE_MAX: 'Phone number must contain maximum 13 digits',
      EMAIL: 'Please enter a valid email address',
      NIK: 'Enter 16 numeric characters.',
      PASSPORT: 'Enter minimum 6 or maximum 10 alphanumeric characters.',
    },
    CONFIRM: {
      BEFORE_POST: 'Pastikan data kamu sudah benar sebelum melanjutkan',
      BUTTON: 'Confirm',
    },
    ERROR: {
      MATCH_NAME: 'Please fill in your name in the contact details first.',
    },
    ATTENTION:
      'Attention: name of passenger must match your passport (international flights), or KTP/SIM (domestic flights). Passenger data cannot be changed after this page.',

    want_to_save: "Want to save even more? Don't forget to log in.",
    passenger_adult: "Adult Passenger",
    passenger_child: "Child Passenger",
    passenger_infant: "Infant Passenger",
    nik: 'ID Card',
    passport: 'Passport',
    order_cant_processed: 'Order cannot be processed Sorry! There was a problem in processing your order. Please select an airline or other available date.',
    return_main_page: 'Return to Main Page',
    transit_for: 'Transit for {time} in {city} ({code})',

    departure: 'Departure',
    return: 'Return',
    departure_price: 'Departure Price',
    return_price: 'Return Price',
  },
  id: {
    BOOKING_DETAIL_HEADING: 'Pemesanan Pesawat Domestik',
    CONTACT_DETAILS: 'Detail Pemesan',
    BOOKING_DETAILS: 'Detail Pemesanan',
    PASSENGER_DETAILS: 'Detail Penumpang',
    FORM: {
      TITLE: 'Titel',
      FIRST: 'Nama Depan',
      MIDDLE: 'Nama Tengah',
      LAST: 'Nama Belakang',
      INFORMATION:
      '<li>Untuk WNI, nama dan NIK harus sama dengan yang terdaftar. Untuk WNA, gunakan nama dan nomor yang tercantum di paspor. </li> <li>Jika kamu tidak memiliki "nama tengah" (contoh: Ari Wibowo), kosongkan bagian nama tengah dan hanya isi nama depan (contoh: Ari) dan nama akhir (contoh: Wibowo)</li> <li>Jika kamu hanya memiliki satu nama (contoh: Kartini), harap mengosongkan nama tengah dan mengisi nama belakang dengan nama depan (contoh: Kartini Kartini).</li>',
      EMAIL: 'Email',
      TELP: 'Nomor Telepon',
      NATIONALITY: 'Kewarganegaraan',
      DOB: 'Tanggal Lahir',
      DATE_FORMAT: 'hh/bb/tt',
      NIK_PLACEHOLDER: 'Nomor NIK minimal 16 karakter',
      IDTYPE: 'Tipe Identitas',
      IDNO: 'Nomor NIK',
      PASSNO: 'Nomor Paspor',
      PASSNO_PLACEHOLDER: 'Min. 6 dan Maks. 10 karakter',
      DOE: 'Tanggal Habis Berlaku',
      COI: 'Negara Yang Mengeluarkan',
      PASSPORT_NOTICE:
        'Perhatian: paspor berlaku minimal 6 bulan dari tanggal kedatangan di destinasi tujuan.',
    },
    PASSENGER: {
      MR: 'Tuan',
      MRS: 'Nyonya',
      MS: 'Nona',
    },
    SAME_AS_CONTACT: 'Sama seperti pemesan',
    VALIDATION: {
      REQUIRED: 'Wajib diisi.',
      NAME: 'Minimal 1 - 50 karakter.',
      MIDDLENAME: 'Maksimal 50 karakter.',
      PHONE_MIN: 'Nomor telepon minimal harus 9 digit',
      PHONE_MAX: 'Nomor telepon maksimal harus 13 digit',
      EMAIL: 'Format email kamu salah',
      NIK: 'Masukkan 16 karakter numerik.',
      PASSPORT: 'Masukkan minimal 6 atau maksimal 10 karakter alfanumerik.',
    },
    CONFIRM: {
      BEFORE_POST: 'Pastikan data kamu sudah benar sebelum melanjutkan',
      BUTTON: 'Konfirmasi',
    },
    ERROR: {
      MATCH_NAME: 'Silahkan isi nama Anda pada detail kontak terlebih dahulu.',
    },
    ATTENTION:
      'Perhatian: nama penumpang harus sama dengan paspor (penerbangan internasional), atau KTP/SIM (penerbangan domestik). Data penumpang tidak dapat diubah setelah halaman ini.',

    want_to_save: "Mau lebih hemat? Jangan lupa log in, ya.",
    passenger_adult: "Penumpang Dewasa",
    passenger_child: "Penumpang Anak",
    passenger_infant: "Penumpang Bayi",
    nik: 'NIK',
    passport: 'Paspor',
    order_cant_processed: 'Pemesanan tidak dapat diproses Mohon maaf! Ada kendala dalam pemrosesan pemesanan kamu. Silakan pilih maskapai atau tanggal lainnya yang tersedia.',
    return_main_page: 'Kembali ke Halaman Utama',
    transit_for: 'Transit selama {time} di {city} ({code})',
    departure: 'Keberangkatan',
    return: 'Kepulangan',
    departure_price: 'Harga Keberangkatan',
    return_price: 'Harga Kepulangan',
  },
};
