# This is a basic workflow to help you get started with Actions

name: MAIN

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ github-page ]
  pull_request:
    branches: [ github-page ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'misteraladin'
        reponame: 'frontend-flight-checkout-wc'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged

